{"name": "Авторизаиця с недействительными учетными данными", "status": "passed", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1723742918810, "stop": 1723742919819}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1723742919819, "stop": 1723742921966}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1723742921966, "stop": 1723742921985}], "start": 1723742918810, "stop": 1723742921986, "uuid": "d72ce584-e1fc-4644-a954-83639a59a976", "historyId": "38e257eb9db8204298dd5e61bdc14efd", "testCaseId": "38e257eb9db8204298dd5e61bdc14efd", "fullName": "ui.tests.login_test#test_login_failure", "labels": [{"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "feature", "value": "Авторизация"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "ui.tests"}, {"name": "suite", "value": "login_test"}, {"name": "host", "value": "WIN-0MTTCQFVLIA"}, {"name": "thread", "value": "7784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "ui.tests.login_test"}]}